# Configure main vm

main_boxes = [
    {
        :name => "main1",
        :eth => "192.168.33.10",
        :mem => "2048",
        :cpu => "2",
        :disk => "20GB"
    }
]

worker_boxes = [
    {
        :name => "worker1",
        :eth => "192.168.33.20",
        :mem => "1024",
        :cpu => "1",
        :disk => "20GB"
    }
]

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_version="3.2.18"

    config.vm.define "main" do |main|
        ## main configuration
        main.vm.hostname = "main"
        main.vm.network "private_network", ip: "192.168.33.10"
        main.vm.disk :disk, size: "20GB", primary: true
        main.vm.provision :ansible do |ansible|
            ansible.playbook = "../ansible/main-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.33.10",
                node_type: "main"
            }
        end

        main.vm.provider :virtualbox do |vb|
            vb.name = "main"
            vb.memory = "2048"
            vb.cpus = "2"
        end
    end

    worker_boxes.each do |vbx| 
        config.vm.define vbx[:name] do |worker|

            ##worker configuration
            worker.vm.network "private_network", ip: vbx[:eth]
            worker.vm.disk :disk, size: vbx[:disk], primary: true

            worker.vm.provider :virtualbox do |vb|
                vb.name = vbx[:name]
                vb.memory = vbx[:mem]
                vb.cpus = vbx[:cpu]
            end

            worker.vm.provision :ansible do |ansible|
                ansible.playbook = "../ansible/main-playbook.yml"
                ansible.extra_vars = {
                    node_ip: vbx[:eth],
                    node_type: "worker"
                }
            end
        end
    end

end