---

- hosts: all
  become: yes
  tasks:
    - name: Install Vim
      apt:
        name: vim
        state: present

    - name: Vim version
      command: |
        vim --version
      register: vim_version

    - debug:
        msg: "{{ vim_version }}"